# -*- coding: utf-8 -*-
"""Deep Learning A Z Convolucional - MNIST simples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18YC5FuhcYRTjSAW9OiNCo_oazB-rBNon

# Deep Learning A Z Convolucional - MNIST simples
"""

!pip install tensorflow==2.21.0

import tensorflow as tf
import keras
import matplotlib
import numpy as np

tf.__version__, keras.__version__, matplotlib.__version__, np.__version__

from tensorflow.keras.datasets import mnist
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer, Dense, Flatten, Dropout, Conv2D, MaxPooling2D, BatchNormalization
from tensorflow.keras import utils as np_utils
import matplotlib.pyplot as plt

(X_treinamento, y_treinamento), (X_teste, y_teste) = cifar10.load_data()

X_treinamento.shape, X_teste.shape

32 * 32

X_treinamento, X_treinamento.max()

y_treinamento

plt.imshow(X_treinamento[0], cmap='gray')
plt.title('Classe ' + str(y_treinamento[0]))

X_treinamento.shape[0]

X_treinamento = X_treinamento.reshape(X_treinamento.shape[0], 32, 32, 3)

X_teste = X_teste.reshape(X_teste.shape[0], 32, 32, 3)

X_treinamento.shape, X_teste.shape

X_treinamento = X_treinamento.astype('float32')

X_teste = X_teste.astype('float32')

X_treinamento /= 255
X_teste /= 255

X_treinamento.max(), X_treinamento.min()

y_treinamento

y_treinamento = np_utils.to_categorical(y_treinamento, 10)
y_teste = np_utils.to_categorical(y_teste, 10)

y_treinamento

y_treinamento[2]

rede_neural = Sequential()

rede_neural.add(InputLayer(shape =(32, 32, 3)))

rede_neural.add(Conv2D(filters = 32, kernel_size = (3, 3), activation = 'relu'))
rede_neural.add(BatchNormalization())
rede_neural.add(MaxPooling2D(pool_size = (2, 2)))

rede_neural.add(Conv2D(filters = 32, kernel_size = (3, 3), activation = 'relu'))
rede_neural.add(BatchNormalization())
rede_neural.add(MaxPooling2D(pool_size = (2, 2)))

rede_neural.add(Flatten())

rede_neural.add(Dense(units = 128, activation = 'relu'))
rede_neural.add(Dropout(0.2))
rede_neural.add(Dense(units = 128, activation = 'relu'))
rede_neural.add(Dropout(0.2))
rede_neural.add(Dense(units = 10, activation = 'softmax'))

13 * 13 * 32

(5408 + 10) / 2

rede_neural.summary()

rede_neural.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

rede_neural.fit(X_treinamento, y_treinamento, batch_size = 128,
                epochs = 20, validation_data = (X_teste, y_teste))

resultado = rede_neural.evaluate(X_teste, y_teste)

resultado